# Travis-CI configuration file

notifications:
  email:
    - robert.link@pnnl.gov

language: r
cache: packages
os:
  - linux
  - osx
dist: trusty
sudo: required

before-install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  
r_binary_packages:
  - rgdal
  - rgeos
  - sp

addons:
  apt:
    packages:
      - libhdf5-7
      - libhdf5-dev
      - proj-data
      - proj-bin

r_github_packages:
  - jimhester/covr

#after_success:
#  - Rscript -e 'library(covr);codecov(function_exclusions = "atest")'
