# Travis-CI configuration file

language: r
warnings_are_errors: true
#sudo: required
cache: packages

r_github_packages:
  - jimhester/covr
  - hrbrmstr/ggalt
  
#after_success:
#  - Rscript -e 'library(covr);codecov(function_exclusions = "atest")'
