language: r

r:
  - release

cache: packages

os:
#  - linux
  - osx

sudo: required

dist: trusty

r_github_packages:
  - tidyverse/ggplot2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get --yes --force-yes update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev; fi
