language: r

r:
  - release
  - oldrel

#  - devel

# r_github_packages: tidyverse/dplyr 

cache: packages

sudo: required

dist: trusty

r_github_packages:
  - tidyverse/ggplot2

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev